A/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

account/urls.py
from django.urls import path
from . import views

app_name = 'account'
urlpatterns = [
    path('register/', views.UserRegisterView.as_view(), name='user_register'),
    path('login/', views.UserLoginView.as_view(), name='user_login'),
    path('logout', views.UserLogoutView.as_view(), name='user_logout'),
    path('profile/<int:user_id>/', views.UserProfileView.as_view(), name='user_profile'),
]

core/urls.py
from django.urls import path
from . import views
from post import views
app_name = 'home'
urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('post/<int:post_id>/<slug:post_slug>/',views.PostDetailView.as_view(), name='post_detail'),
    path('post/delete/<int:post_id/', views.PostDeleteView.as_view(), name='post_delete'),
    path('post/delete/<int:post_id', views.PostUpdateViwe.as_view(),name='post_update')
]

post/urls.py
from django.urls import path
from . import views
from post import views
app_name = 'home'
urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('post/<int:post_id>/<slug:post_slug>/',views.PostDetailView.as_view(), name='post_detail'),
    path('post/delete/<int:post_id/', views.PostDeleteView.as_view(), name='post_delete'),
    path('post/delete/<int:post_id', views.PostUpdateViwe.as_view(),name='post_update')
]

account/models.py
from django.db import models

# Create your models here.

post/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Post(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    caption = models.CharField()
    slug = models.CharField()
    created_date = models.DateField(auto_now_add=True)
    updated_date = models.DateField(auto_now=True)


    def __str__(self):
        return f'{self.slug} - {self.updated_date}'

    def get_absolute_url(self):
        return reverse('home:post_detail', args=(self.id, self.slug))

account/forms.py
from django import forms
from django.contrib.auth.models import User


class UserRegistrationForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class': 'form-control'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    password1 = forms.CharField(label='confing password', widget=forms.PasswordInput(attrs={'class': 'form-control'}))

    def clean_email(self):
        email = self.cleaned_data('email')
        user = User.objects.filter(email=email).exists()
        if user:
            raise ValueError('this email already exists')
        return email


    def clean_username(self):
        username = self.cleaned_data('username')
        user = User.objects.filter(username=username).exists()
        if user:
            raise ValueError('this username already exists')
        return username


    def clean(self):
        cd = super().clean()
        p = cd.get('password')
        p1 = cd.get('password1')

        if p and p1 and p != p1:
            raise ValueError('password must match')

class UserLoginForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}))

post/forms.py
from django import forms
from .models import Post

class FormUpdatePost(forms.Form):
    class Meta:
        model = Post
        fields = ('body',)

account/views.py
from django.shortcuts import render, redirect
from django.views import View
from .forms import UserRegistrationForm, UserLoginForm
from django.contrib.auth.models import User
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.mixins import LoginRequiredMixin
from post.models import Post



class UserRegisterView(View):
    form_class = UserRegistrationForm

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authentucated:
            return redirect('home:home')
        return super().dispatch(request, *args, **kwargs)

    def get(self, request):
        form = self.form_class()
        return render(request, 'account/register.html', {'form': form})

    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            User.objects.create_user(cd['username'], cd['email'], cd['password'])
            messages.success(request, ' you register is successfully', 'success')
            return redirect('home:home')
        return render(request, 'account/register.html', {'form': form})


class UserLoginView(View):
    form_class = UserLoginForm
    templates_name = 'account/login.html'

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authentucated:
            return redirect('home:home')
        return super().dispatch(request, *args, **kwargs)


    def get(self, request):
        form = self.form_class
        return render(request, self.templates_name, {'form': form})



    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = authenticate(request, username=cd['username'], password=cd['password'])
            if user is not None:
                login(request, user)
                messages.success(request, 'your logged is successfully')
                return redirect('home:home')
            messages.error(request, 'username or password is wrong', 'warning')
        return render(request, self.templates_name, {'form': form})






class UserLogoutView(LoginRequiredMixin, View):

    def get(self, request):
        logout(request)
        messages.success(request, 'your logout successfully', 'success')
        return redirect('home:home')





class UserProfileView(LoginRequiredMixin, View):

    def get(self, request, user_id):
        user = User.objects.get(pk=user_id)
        post = Post.object.filter()
        return render(request, 'account/profile.html', {'user': user, 'posts': post})

core/views.py
from django.shortcuts import render
from django.views import View
from post.models import Post


# Create your views here.


class HomeView(View):
    def get(self, request):
        post = Post.objects.all()
        return render(request, 'home/index.html', {'post': post})

post/views.py
from django.shortcuts import render, redirect
from django.views import View
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from post.models import Post





class PostDeleteView(LoginRequiredMixin, View):
    def get(self, request, post_id):
        post = Post.objects.get(pk=post_id)
        if post.user.id == request.user.id:
            post.delete()
            messages.succes(request, 'post delete successfully', 'success')
        else:
            messages.error(request, 'you can delete this post', 'danger')
        return redirect('home:home')



class PostUpdateView(LoginRequiredMixin, View):

    def setup(self, request, *args, **kwargs):
        self.instanse = Post.objects.get(pk=kwargs['post_id'])
        return super().setup(request, *args, **kwargs)

    def dispatch(self, request, *args, **kwargs):
        post = Post.abjects.get(pk=kwargs['post_id'])
        if not post.user.id == request.user.id:
            messages.error(request, 'you cant update this post')
            return redirect('home:home')
        return super().dispatch(request, *args, **kwargs)
    def get(self, request, *args, **kwargs):
        post = self.post_instance
        form = self.form_class(isinstance=post)
        return render(request, 'home/update.html', {'form':form})



    def post(self, request, *args, **kwargs):
        post = self.post_instance
        form = self.form_class(request.POST, isinstance=post)
        if form.is_valid():
            new_post = form.save(request.POST, instance=post)
            new_post.slug = slugify(from.cleaned_data['body'][:30])
            new_post.save()
            messages.succes(request, 'you update this post success')
            return redirects('home:post_detail', post.id, post.slug)

account/templates/login.html
{% extends 'base.html' %}
{% block content %}
    <h2>login</h2>

    <form action="" method="post" class="col-md-4" novalidate>
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="login">
    </form>

{% endblock %}

account/templates/profile.html
{% extends 'base.html' %}

{% block content %}
    <h2 class=" text-center">{{ user.username}}</h2>
        {% for post in posts %}

        <a href="{% url 'home:post_detail' %}" class="card-body">
            {{ post.body|truncatewords:8 }}
        </a>

    {% endfor %}
{% endblock %}

account/templates/register.html
{% extends 'base.html' %}
{% block content %}
    <h2>Register</h2>

    <form action="" method="post" class="col-md-4" novalidate>
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="register">
    </form>

{% endblock %}

core/templates/home/detail.html
{% extend 'base.html' %}

{% block content %}
    {% if request.user.id == post.user.id %}
        <a href="{% url 'home:post_delete' post.id %}" class="btn btn-danger">Delete</a>
        <a href="{% url 'home:post_update' post.id %}" class="btn btn-info">Update</a>
    {% endif %}
    <p><a href="{% url 'account:user_profile' post.user.id %}">{{ post.user.username }}</a>  - {{ post.update }}</p>
    <p>{{ post.body }}</p>

{% endblock %}

core/templates/home/index.html
{% extends 'base.html' %}

{% block content %}
<div class="card">
    {% for post in posts %}

        <a href="{{ post.get_absolute_url }}" class="card-body">
            {{ post.body|truncatewords:8 }}
        </a>

    {% endfor %}
</div>


{% endblock %}

core/templates/home/update.html
{% extend 'base.html' %}

{% block contnet %}
    <form action="" method="post" novalidate>
        {% csrf_token %}
        {{ from.as_p}}
        <input type="submit", value="Update">
    </form>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>home</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
</head>
<body>
    {% include 'inc/navbar.html' %}
    <div>
        {% block content %} {% endblock %}
        {% include 'inc/messages.html' %}
    </div>

</body>
</html>

templates/inc/messages.html
{% if messages %}
    {% for msg in messages %}
        <p class="alert alert-{{ msg.tags }}">
            {{ msg }}
        </p>
    {% endfor %}
{% endif %}

templates/inc/navbar.html
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Features</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Pricing</a>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled">Disabled</a>
        </li>
      </ul>
    </div>
  </div>
</nav>